spring:
  application:
    name: ${APP_NAME:cqrs-query}

  # MongoDB 설정 (Read DB)
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB:telecomdb}?authSource=admin

# Event Hub 설정
eventhub:
  plan-connection-string: ${EVENT_HUB_PLAN_CONNECTION_STRING}
  usage-connection-string: ${EVENT_HUB_USAGE_CONNECTION_STRING}
  plan-hub-name: ${EVENT_HUB_PLAN_NAME:phone-plan-events}
  usage-hub-name: ${EVENT_HUB_USAGE_NAME:phone-usage-events}
  batch-size: 100
  checkpoint-interval: 5000

# Azure Storage 설정
azure:
  storage:
    connection-string: ${STORAGE_CONNECTION_STRING:UseDevelopmentStorage=true}
    plan-container: plan-checkpoints
    usage-container: usage-checkpoints

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# 서버 포트 설정
server:
  port: ${SERVER_PORT:8080}

# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# 로깅 설정
logging:
  level:
    root: INFO
    com.telecom.cqrs: ${LOG_LEVEL:INFO}
    com.azure.messaging.eventhubs: INFO
    org.hibernate.SQL: ${LOG_LEVEL:INFO}
    org.springframework.data.mongodb: ${LOG_LEVEL:INFO}
