spring:
  application:
    name: ${APP_NAME:cqrs-query}

  # MongoDB 설정 (Read DB)
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DB:telecomdb}?authSource=admin

  # Event Hub 설정
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${EVENT_HUB_CONNECTION_STRING}";
    bootstrap-servers: ${EVENT_HUB_NAMESPACE}.servicebus.windows.net:9093

azure:
  storage:
    connection-string: ${STORAGE_CONNECTION_STRING:UseDevelopmentStorage=true}
    name: phone-plan-events

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# 서버 포트 설정 (spring 설정과 같은 레벨로 이동)
server:
  port: ${SERVER_PORT:8080}


logging:
  level:
    com.telecom: TRACE
    org.hibernate.SQL: TRACE
